version: "2.2"
services:
  jobmanager:
    image: ravitomar7/flink-kafka:v2
    ports:
      - "8081:8081"
      - "8083:8083"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  taskmanager:
    image: ravitomar7/flink-kafka:v2
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4       
  sql-client:
    image: ravitomar7/flink-kafka:v2
    command: bin/sql-client.sh
    depends_on:
      - taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager     
    
  # postgres:
  #   image: postgres:11.2-alpine
  #   restart: always
  #   container_name: postgres
  #   volumes:
  #     - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #   ports:
  #     - 5432:5432
 
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
        